export const CreateBlogPostView = () => import('./CreateBlogPost.view.vue')
export const HomeView = () => import('./MainHome.view.vue')
export const SingleBlogPost = () => import('./SingleBlog.view.vue')
export const DisplayBlogsWithTag = () => import('./DisplayBlogsWithTag.view.vue')
export const NotFound = () => import('./404.vue')
export const ViewAllBlogPosts = () => import('./ViewAllBlogPosts.vue')
export const ViewAuthorBlogs = () => import('./ViewAuthorBlogs.view.vue')
export const MyAccount = () => import('./MyAccount.view.vue')