export const CreateBlogPostView = async () => await import('./CreateBlogPost.view.vue')
export const HomeView = async () => await import('./MainHome.view.vue')
export const SingleBlogPost = async () => await import('./SingleBlog.view.vue')
export const DisplayBlogsWithTag = async () => await import('./DisplayBlogsWithTag.view.vue')
export const NotFound = async () => await import('./404.vue')
export const ViewAllBlogPosts = async () => await import('./ViewAllBlogPosts.vue')