export { default as LoginPopUp } from './login/logInPopUp.vue'
export { default as LogoutPopUp } from './logout/logoutPopUp.vue'
export { default as RegisterPopUp } from './register/RegisterPopUp.vue'
export { default as UserMenu } from './userMenu/UserMenu.vue'
export { default as UserAvatarDisplay } from './userMenu/UserAvatarDisplay.vue'
export { default as LoginWithGoogleComponent } from './OAuth/logInWithGoogle.component.vue'
